const STOPWORDS = {
  fr: [
    // Déterminants & articles
    "le",
    "la",
    "les",
    "un",
    "une",
    "des",
    "du",
    "de",
    "d",
    "au",
    "aux",
    "l",
    "lequel",
    "laquelle",
    "lesquels",
    "lesquelles",

    // Prépositions
    "a",
    "à",
    "en",
    "dans",
    "sur",
    "sous",
    "avec",
    "sans",
    "chez",
    "pour",
    "par",
    "vers",
    "entre",
    "depuis",
    "jusque",
    "jusqu",
    "jusqu'à",
    "pendant",
    "après",
    "avant",
    "contre",
    "selon",

    // Conjonctions
    "et",
    "ou",
    "mais",
    "donc",
    "or",
    "ni",
    "car",
    "que",
    "qu",
    "qu'",

    // Relatifs / interrogatifs
    "qui",
    "quoi",
    "dont",
    "où",
    "quand",
    "comment",
    "pourquoi",

    // Pronoms
    "je",
    "tu",
    "il",
    "elle",
    "on",
    "nous",
    "vous",
    "ils",
    "elles",
    "me",
    "te",
    "se",
    "moi",
    "toi",
    "lui",
    "leur",
    "y",
    "en",

    // Possessifs
    "mon",
    "ma",
    "mes",
    "ton",
    "ta",
    "tes",
    "son",
    "sa",
    "ses",
    "notre",
    "nos",
    "votre",
    "vos",
    "leurs",

    // Verbes être / avoir (formes courantes)
    "etre",
    "être",
    "suis",
    "es",
    "est",
    "sommes",
    "etes",
    "êtes",
    "sont",
    "avoir",
    "ai",
    "as",
    "a",
    "avons",
    "avez",
    "ont",

    // Autres verbes très fréquents
    "fait",
    "faire",
    "aller",
    "va",
    "vais",
    "vont",
    "peut",
    "peux",
    "peuvent",

    // Adverbes très génériques
    "plus",
    "bien",
    "tres",
    "très",
    "beaucoup",
    "aussi",
    "meme",
    "même",
    "déjà",
    "toujours",
    "encore",
  ],

  en: [
    // Articles
    "a",
    "an",
    "the",

    // Prépositions
    "in",
    "on",
    "at",
    "to",
    "for",
    "with",
    "without",
    "from",
    "by",
    "about",
    "into",
    "after",
    "before",
    "between",
    "through",
    "during",
    "over",
    "under",

    // Conjonctions
    "and",
    "or",
    "but",
    "nor",
    "so",
    "yet",
    "because",
    "that",
    "which",
    "who",
    "whom",
    "where",
    "when",
    "why",
    "how",

    // Pronoms
    "i",
    "you",
    "he",
    "she",
    "it",
    "we",
    "they",
    "me",
    "him",
    "her",
    "us",
    "them",
    "this",
    "that",
    "these",
    "those",

    // Verbes très fréquents
    "be",
    "am",
    "is",
    "are",
    "was",
    "were",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "can",
    "could",
    "may",
    "might",
    "shall",
    "should",

    // Adverbes génériques
    "very",
    "much",
    "more",
    "also",
    "too",
    "just",
    "already",
    "always",
  ],
};

const STRONG_WORDS = {
  fr: [
    // ----- JOURS -----
    "lundi",
    "mardi",
    "mercredi",
    "jeudi",
    "vendredi",
    "samedi",
    "dimanche",

    // ----- TEMPS RELATIF -----
    "aujourdhui",
    "aujourd",
    "aujourd'hui",
    "hier",
    "demain",
    "maintenant",
    "tout_de_suite",
    "tout-de-suite",
    "bientot",
    "bientôt",

    // ----- MOMENTS DE LA JOURNÉE (SANS CHIFFRES) -----
    "matin",
    "matinee",
    "matinée",
    "midi",
    "apres-midi",
    "après-midi",
    "fin_dapres-midi",
    "fin_daprès-midi",
    "soir",
    "soiree",
    "soirée",
    "nuit",
    "milieu_de_nuit",
    "pleine_nuit",
    "aube",
    "lever_du_jour",
    "crepuscule",
    "crépuscule",

    // ----- PÉRIODES -----
    "journee",
    "journée",
    "semaine",
    "weekend",
    "week-end",
    "week_end",
    "mois",
    "annee",
    "année",
    "vacances",
    "conges",
    "congés",

    // ----- ÉVÉNEMENTS (forte intention) -----
    "anniversaire",
    "rendez-vous",
    "rdv",
    "fete",
    "fête",
    "soiree",
    "soirée",
    "mariage",
    "bapteme",
    "baptême",
    "naissance",
    "enterrement",
    "funerailles",
    "funérailles",
    "reunion",
    "réunion",
    "entretien",
    "exam",
    "examen",
    "controle",
    "contrôle",
    "deplacement",
    "déplacement",
    "voyage",
    "concert",
    "spectacle",
    "match",
    "compet",
    "compétition",
    "ceremonie",
    "cérémonie",
    "celebration",
    "célébration",
    "fete_de_famille",
    "fête_de_famille",
    "reveillon",
    "réveillon",
    "noel",
    "noël",
    "nouvel_an",
  ],
  en: [
    // ----- DAYS -----
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",

    // ----- RELATIVE TIME -----
    "today",
    "yesterday",
    "tomorrow",
    "now",
    "right_now",
    "soon",

    // ----- TIME OF DAY (no numbers) -----
    "morning",
    "midday",
    "noon",
    "afternoon",
    "late_afternoon",
    "evening",
    "night",
    "midnight",
    "dawn",
    "sunrise",
    "dusk",

    // ----- PERIODS -----
    "day",
    "week",
    "weekend",
    "month",
    "year",
    "holiday",
    "holidays",
    "vacation",
    "break",

    // ----- EVENTS -----
    "birthday",
    "appointment",
    "meeting",
    "party",
    "wedding",
    "baptism",
    "birth",
    "funeral",
    "interview",
    "exam",
    "test",
    "trip",
    "travel",
    "journey",
    "concert",
    "show",
    "spectacle",
    "match",
    "game",
    "competition",
    "ceremony",
    "celebration",
    "family_gathering",
    "christmas",
    "new_year",
  ],
};

const WEAK_WORDS = {
  fr: [
    "quelques",
    "plusieurs",
    "certains",
    "certaines",
    "un_peu",
    "un_peu_de",
    "beaucoup_de",
    "plein_de",
    "petit",
    "petite",
    "petits",
    "petites",
    "grand",
    "grande",
    "grands",
    "grandes",
    "trop",
    "assez",
    "encore",
    "juste",
    "environ",
    "presque",
    "quasi",
    "plutot",
    "plutôt",
  ],

  en: [
    "some",
    "several",
    "many",
    "a_few",
    "a_bit",
    "a_lot",
    "small",
    "little",
    "big",
    "large",
    "too",
    "enough",
    "still",
    "just",
    "about",
    "almost",
    "nearly",
    "rather",
  ],
};

export const wordCollection = { STOPWORDS, STRONG_WORDS, WEAK_WORDS };
